apiVersion: batch/v1
kind: Job
metadata:
  name: pvc-transfer-job
  namespace: eepereira #colocar o namespace de vocês 
spec:
  backoffLimit: 2
  template:
    spec:
      imagePullSecrets:         
        - name: gitea-key
      nodeName: vanhalen #pode apagar se tanto faz em qual nodo for cair
      restartPolicy: Never
      # initContainers:
      # - name: raise-ulimit
      #   image: busybox:latest
      #   securityContext:
      #     capabilities:
      #       add:
      #       - SYS_RESOURCE
      #   command:
      #   - sh
      #   - -c
      #   - "ulimit -n 1048576"
      containers:
      - name: exporter
        image: busybox:latest
        command: ["sh", "-c"]
        args:
        - |
          echo "=== PVC Exporter Ready ==="
          echo "Copy your files using kubectl cp, then press ENTER in this terminal to terminate the pod."
          read -p "Press ENTER to finish..." unused_var
          echo "Exiting..."
        stdin: true
        tty: true
        resources: #muito importante colocar um limite, evita problemas
          requests:
            cpu: 1
            memory: 2Gi
            nvidia.com/gpu: 0
          limits:
            cpu: 1
            memory: 4Gi
            nvidia.com/gpu: 0
          # requests:
          #   cpu: 1
          #   memory: 8Gi
          #   nvidia.com/gpu: 0
          # limits:
          #   cpu: 2
          #   memory: 16Gi
          #   nvidia.com/gpu: 0
        volumeMounts:
        # Monta as 3 pastas na raiz onde o main.py é executado (/app/src)
        - name: program-data # Igual ao do volumes abaixo
          mountPath: /app/Logs  # Nome no container
          subPath: Logs # Nome da pasta no volume
        - name: program-data
          mountPath: /app/Models  # Substitua pelo nome da pasta 2
          subPath: Models
        - name: program-data
          mountPath: /app/Results  # Substitua pelo nome da pasta 3
          subPath: Results
        - name: program-data # Igual ao do volumes abaixo
          mountPath: /app/index  # Nome no container
          subPath: index # Nome da pasta no volume
          readOnly: false
        - name: program-data # Igual ao do volumes abaixo
          mountPath: /app/documents  # Nome no container
          subPath: documents # Nome da pasta no volume
          readOnly: false
        - name: program-data # Igual ao do volumes abaixo
          mountPath: /app/models  # Nome no container
          subPath: models # Nome da pasta no volume
          readOnly: false
        - name: program-data # Igual ao do volumes abaixo
          mountPath: /app/results  # Nome no container
          subPath: results # Nome da pasta no volume
          readOnly: false
      volumes:
      - name: program-data
        persistentVolumeClaim:
          claimName: index-pvc # Nome do pvc

# kubectl apply -f job.yaml